spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: system
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
mybatis:
  configLocation:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.bookmybatis.entity
  mapper-locations: mappers/*.xml